Meme ideas:<br><ul>
 -> look up weird cases of advanced indexing and use in rabbit 123 meme<br>
 -> train dilemma<br>
 -> immediate termination feat: John Vivilecchia<br>
 -> food at Maseeh<br>
 -> baby ryan talking about broadcasting///smh i was too late<br>
 -> how the different students see each other</ul>
 

machine audio broadcasting


<ol>
k-means/hyperparameters<br>

linear classifiers<br>

gradients and chain rule<br>

score loss models<br>
</ol>



In [8]:
import numpy as np
bumpy.arange(3**3).reshape(3,3,3);

<h2>basic indexing</h2>

x[(i, j, k)] need a longer index for more dimensions, normally done with tuple<br>i,j,k can be a <ul>slice<br>int<br>ellipsis<br>newaxis</ul>

<h2>advanced indexing</h2>

in general broadcasting will try to return an array with a similar shape to the input array.

In [49]:
x = np.arange(3**3).reshape(3,3,3)

In [10]:
x[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
x[1,:,::2]

array([[ 9, 11],
       [12, 14],
       [15, 17]])

In [20]:
x[(0,0,1), (0,0,1), (0,1,1)]

array([ 0,  1, 13])

In [30]:
o = (x <2 | x == 13)
x[o]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [34]:
x[x&2==0]**=2

In [36]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [50]:
x[(x%2==1)] = x[x%2==1][::-1]
x


array([[[ 0, 25,  2],
        [23,  4, 21],
        [ 6, 19,  8]],

       [[17, 10, 15],
        [12, 13, 14],
        [11, 16,  9]],

       [[18,  7, 20],
        [ 5, 22,  3],
        [24,  1, 26]]])